spring.datasource.url               = jdbc:mysql://localhost:3306/emp
spring.datasource.username          = valvarez
spring.datasource.password          = valvarez1234
spring.jpa.hibernate.ddl-auto       = update
spring.jpa.show-sql                 = true